### ISSUE TITLE
하드웨어 라이선스

### ISSUE THREAD

**Issue by edp1096** [ifndef77/m3DP_Printed_by_PRUSA#1]
안녕하세요.
OC카페에서 타고 넘어왔습니다.

좋은 자료 공유해주셔서 감사합니다.

Marlin의 라이선스는 GPL로 알고 있는데,
작업하신 하드웨어 쪽 라이선스도 소프트웨어와 동일하게 GPL인지 아니면 다른 라이선스인지 알고 싶습니다.

**Comment by ifndef77** [comment]
하드웨어 관련 라이선스 표기 업데이트 했습니다.
